using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_API_Service.Models {
    public class DBSchema {


            public int took { get; set; }
            public bool timed_out { get; set; }
            public _Shards _shards { get; set; }
            public Hits hits { get; set; }
        

        public class _Shards {
            public int total { get; set; }
            public int successful { get; set; }
            public int skipped { get; set; }
            public int failed { get; set; }
        }

        public class Hits {
            public Total total { get; set; }
            public float max_score { get; set; }
            public Hit[] hits { get; set; }
        }

        public class Total {
            public int value { get; set; }
            public string relation { get; set; }
        }

        public class Hit {
            public string _index { get; set; }
            public string _type { get; set; }
            public string _id { get; set; }
            public float _score { get; set; }
            public _Source _source { get; set; }
        }

        public class _Source {

            public string action { get; set; }
            public string actionkeyword { get; set; }
            public string activitiesskippedcount { get; set; }
            public string activitiesexceptionsclassName { get; set; }
            public string activitiesexceptionsclassNamekeyword { get; set; }
            public string activitiesexceptionsclientConnectionId { get; set; }
            public string activitiesexceptionsclientConnectionIdkeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkBaseHelpUrl { get; set; }
            public string activitiesexceptionsdatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkEvtID { get; set; }
            public string activitiesexceptionsdatahelpLinkEvtIDkeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkEvtSrc { get; set; }
            public string activitiesexceptionsdatahelpLinkEvtSrckeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkLinkId { get; set; }
            public string activitiesexceptionsdatahelpLinkLinkIdkeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkProdName { get; set; }
            public string activitiesexceptionsdatahelpLinkProdNamekeyword { get; set; }
            public string activitiesexceptionsdatahelpLinkProdVer { get; set; }
            public string activitiesexceptionsdatahelpLinkProdVerkeyword { get; set; }
            public string activitiesexceptionserrorsclass { get; set; }
            public string activitiesexceptionserrorslineNumber { get; set; }
            public string activitiesexceptionserrorsmessage { get; set; }
            public string activitiesexceptionserrorsmessagekeyword { get; set; }
            public string activitiesexceptionserrorsnumber { get; set; }
            public string activitiesexceptionserrorsprocedure { get; set; }
            public string activitiesexceptionserrorsprocedurekeyword { get; set; }
            public string activitiesexceptionserrorsserver { get; set; }
            public string activitiesexceptionserrorsserverkeyword { get; set; }
            public string activitiesexceptionserrorssource { get; set; }
            public string activitiesexceptionserrorssourcekeyword { get; set; }
            public string activitiesexceptionserrorsstate { get; set; }
            public string activitiesexceptionsexceptionMethod { get; set; }
            public string activitiesexceptionsexceptionMethodkeyword { get; set; }
            public string activitiesexceptionsfileNotFound_FileName { get; set; }
            public string activitiesexceptionsfileNotFound_FileNamekeyword { get; set; }
            public string activitiesexceptionshResult { get; set; }
            public string activitiesexceptionsinnerExceptionclassName { get; set; }
            public string activitiesexceptionsinnerExceptionclassNamekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionclientConnectionId { get; set; }
            public string activitiesexceptionsinnerExceptionclientConnectionIdkeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkEvtID { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkLinkId { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkProdName { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkProdVer { get; set; }
            public string activitiesexceptionsinnerExceptiondatahelpLinkProdVerkeyword { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsclass { get; set; }
            public string activitiesexceptionsinnerExceptionerrorslineNumber { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsmessage { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsmessagekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsnumber { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsprocedure { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsprocedurekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsserver { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsserverkeyword { get; set; }
            public string activitiesexceptionsinnerExceptionerrorssource { get; set; }
            public string activitiesexceptionsinnerExceptionerrorssourcekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionerrorsstate { get; set; }
            public string activitiesexceptionsinnerExceptionexceptionMethod { get; set; }
            public string activitiesexceptionsinnerExceptionexceptionMethodkeyword { get; set; }
            public string activitiesexceptionsinnerExceptionhResult { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionclassName { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionclientConnectionId { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionclientConnectionIdkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkEvtID { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkLinkId { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkProdName { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkProdVer { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptiondatahelpLinkProdVerkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsclass { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorslineNumber { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsmessage { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsmessagekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsnumber { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsprocedure { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsprocedurekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsserver { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsserverkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorssource { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorssourcekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionerrorsstate { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionexceptionMethod { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionexceptionMethodkeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionhResult { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionclassName { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionhResult { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionmessage { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionmessage { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionsource { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionsourcekeyword { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionstackTraceString { get; set; }
            public string activitiesexceptionsinnerExceptioninnerExceptionstackTraceStringkeyword { get; set; }
            public string activitiesexceptionsinnerExceptionmessage { get; set; }
            public string activitiesexceptionsinnerExceptionmessagekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionnativeErrorCode { get; set; }
            public string activitiesexceptionsinnerExceptionremoteStackIndex { get; set; }
            public string activitiesexceptionsinnerExceptionsource { get; set; }
            public string activitiesexceptionsinnerExceptionsourcekeyword { get; set; }
            public string activitiesexceptionsinnerExceptionstackTraceString { get; set; }
            public string activitiesexceptionsinnerExceptionstackTraceStringkeyword { get; set; }
            public string activitiesexceptionsmessage { get; set; }
            public string activitiesexceptionsmessagekeyword { get; set; }
            public string activitiesexceptionsremoteStackIndex { get; set; }
            public string activitiesexceptionssource { get; set; }
            public string activitiesexceptionssourcekeyword { get; set; }
            public string activitiesexceptionsstackTraceString { get; set; }
            public string activitiesexceptionsstackTraceStringkeyword { get; set; }
            public string activitiesexecutionTime { get; set; }
            public string activitiesreadableName { get; set; }
            public string activitiesreadableNamekeyword { get; set; }
            public string activitiestype { get; set; }
            public string activitiestypekeyword { get; set; }
            public string activitieswarnings { get; set; }
            public string activitieswarningskeyword { get; set; }
            public string activityId { get; set; }
            public string activityType { get; set; }
            public string activityTypekeyword { get; set; }
            public string argumentscartidentificationcustomerNumber { get; set; }
            public string argumentscartidentificationcustomerNumberkeyword { get; set; }
            public string argumentscartorderId { get; set; }
            public string argumentscartorderIdkeyword { get; set; }
            public string argumentsorderorderId { get; set; }
            public string caller { get; set; }
            public string callerkeyword { get; set; }
            public string cartId { get; set; }
            public string cartIdkeyword { get; set; }
            public string _class { get; set; }
            public string classkeyword { get; set; }
            public string command { get; set; }
            public string commandkeyword { get; set; }
            public string commandType { get; set; }
            public string commandTypekeyword { get; set; }
            public string controller { get; set; }
            public string controllerkeyword { get; set; }
            public string cropNumber { get; set; }
            public string cropNumberkeyword { get; set; }
            public string customer { get; set; }
            public string customerkeyword { get; set; }
            public string customerNumber { get; set; }
            public string customerNumberkeyword { get; set; }
            public string duration { get; set; }
            public string emails { get; set; }
            public string emailskeyword { get; set; }
            public string entryCount { get; set; }
            public string exception { get; set; }
            public string exception_httpCode { get; set; }
            public string exceptionaction { get; set; }
            public string exceptionactionkeyword { get; set; }
            public string exceptionargs { get; set; }
            public string exceptionargskeyword { get; set; }
            public string exceptionclassName { get; set; }
            public string exceptionclassNamekeyword { get; set; }
            public string exceptionclientConnectionId { get; set; }
            public string exceptionclientConnectionIdkeyword { get; set; }
            public string exceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string exceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string exceptiondatahelpLinkEvtID { get; set; }
            public string exceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string exceptiondatahelpLinkEvtSrc { get; set; }
            public string exceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string exceptiondatahelpLinkLinkId { get; set; }
            public string exceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string exceptiondatahelpLinkProdName { get; set; }
            public string exceptiondatahelpLinkProdNamekeyword { get; set; }
            public string exceptiondatahelpLinkProdVer { get; set; }
            public string exceptiondatahelpLinkProdVerkeyword { get; set; }
            public string exceptiondetailmessage { get; set; }
            public string exceptiondetailmessagekeyword { get; set; }
            public string exceptiondetailstackTrace { get; set; }
            public string exceptiondetailstackTracekeyword { get; set; }
            public string exceptiondetailtype { get; set; }
            public string exceptiondetailtypekeyword { get; set; }
            public string exceptionerrorsclass { get; set; }
            public string exceptionerrorserrorCode { get; set; }
            public string exceptionerrorshelpLink { get; set; }
            public string exceptionerrorshelpLinkkeyword { get; set; }
            public string exceptionerrorslineNumber { get; set; }
            public string exceptionerrorsmessage { get; set; }
            public string exceptionerrorsmessagekeyword { get; set; }
            public string exceptionerrorsnumber { get; set; }
            public string exceptionerrorsprocedure { get; set; }
            public string exceptionerrorsprocedurekeyword { get; set; }
            public string exceptionerrorsserver { get; set; }
            public string exceptionerrorsserverkeyword { get; set; }
            public string exceptionerrorssource { get; set; }
            public string exceptionerrorssourcekeyword { get; set; }
            public string exceptionerrorsstate { get; set; }
            public string exceptionexceptionMethod { get; set; }
            public string exceptionexceptionMethodkeyword { get; set; }
            public string exceptionfailedRecipient { get; set; }
            public string exceptionfailedRecipientkeyword { get; set; }
            public string exceptionhResult { get; set; }
            public string exceptionhelpURL { get; set; }
            public string exceptionhelpURLkeyword { get; set; }
            public string exceptioninnerException_httpCode { get; set; }
            public string exceptioninnerExceptionclassName { get; set; }
            public string exceptioninnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptionclientConnectionId { get; set; }
            public string exceptioninnerExceptionclientConnectionIdkeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string exceptioninnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkEvtID { get; set; }
            public string exceptioninnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string exceptioninnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkLinkId { get; set; }
            public string exceptioninnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkProdName { get; set; }
            public string exceptioninnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string exceptioninnerExceptiondatahelpLinkProdVer { get; set; }
            public string exceptioninnerExceptiondatahelpLinkProdVerkeyword { get; set; }
            public string exceptioninnerExceptionerrorsclass { get; set; }
            public string exceptioninnerExceptionerrorslineNumber { get; set; }
            public string exceptioninnerExceptionerrorsmessage { get; set; }
            public string exceptioninnerExceptionerrorsmessagekeyword { get; set; }
            public string exceptioninnerExceptionerrorsnumber { get; set; }
            public string exceptioninnerExceptionerrorsprocedure { get; set; }
            public string exceptioninnerExceptionerrorsprocedurekeyword { get; set; }
            public string exceptioninnerExceptionerrorsserver { get; set; }
            public string exceptioninnerExceptionerrorsserverkeyword { get; set; }
            public string exceptioninnerExceptionerrorssource { get; set; }
            public string exceptioninnerExceptionerrorssourcekeyword { get; set; }
            public string exceptioninnerExceptionerrorsstate { get; set; }
            public string exceptioninnerExceptionexceptionMethod { get; set; }
            public string exceptioninnerExceptionexceptionMethodkeyword { get; set; }
            public string exceptioninnerExceptionhResult { get; set; }
            public string exceptioninnerExceptionhelpURL { get; set; }
            public string exceptioninnerExceptionhelpURLkeyword { get; set; }
            public string exceptioninnerExceptioninnerException_httpCode { get; set; }
            public string exceptioninnerExceptioninnerExceptionclassName { get; set; }
            public string exceptioninnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionclientConnectionId { get; set; }
            public string exceptioninnerExceptioninnerExceptionclientConnectionIdkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkEvtID { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkLinkId { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkProdName { get; set; }
            public string exceptioninnerExceptioninnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsclass { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorslineNumber { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsmessage { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsmessagekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsnumber { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsprocedure { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsprocedurekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsserver { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsserverkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorssource { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorssourcekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionerrorsstate { get; set; }
            public string exceptioninnerExceptioninnerExceptionexceptionMethod { get; set; }
            public string exceptioninnerExceptioninnerExceptionexceptionMethodkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionhResult { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionclassName { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionclientConnectionId { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionclientConnectionIdkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkEvtID { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkLinkId { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkProdName { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkProdVer { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptiondatahelpLinkProdVerkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsclass { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorslineNumber { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsmessage { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsmessagekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsnumber { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsprocedure { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsprocedurekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsserver { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsserverkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorssource { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorssourcekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionerrorsstate { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionexceptionMethod { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionexceptionMethodkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionhResult { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionclassName { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionhResult { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionmessage { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionmessage { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionsource { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionsourcekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionstackTraceString { get; set; }
            public string exceptioninnerExceptioninnerExceptioninnerExceptionstackTraceStringkeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionmessage { get; set; }
            public string exceptioninnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string exceptioninnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptioninnerExceptionsource { get; set; }
            public string exceptioninnerExceptioninnerExceptionsourcekeyword { get; set; }
            public string exceptioninnerExceptioninnerExceptionstackTraceString { get; set; }
            public string exceptioninnerExceptioninnerExceptionstackTraceStringkeyword { get; set; }
            public string exceptioninnerExceptionmessage { get; set; }
            public string exceptioninnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptionnativeErrorCode { get; set; }
            public string exceptioninnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptionsource { get; set; }
            public string exceptioninnerExceptionsourcekeyword { get; set; }
            public string exceptioninnerExceptionstackTraceString { get; set; }
            public string exceptioninnerExceptionstackTraceStringkeyword { get; set; }
            public string exceptioninnerExceptionwatsonBuckets { get; set; }
            public string exceptioninnerExceptionwatsonBucketsskippedcount { get; set; }
            public string exceptioninnerExceptionsclassName { get; set; }
            public string exceptioninnerExceptionsclassNamekeyword { get; set; }
            public string exceptioninnerExceptionsexceptionMethod { get; set; }
            public string exceptioninnerExceptionsexceptionMethodkeyword { get; set; }
            public string exceptioninnerExceptionshResult { get; set; }
            public string exceptioninnerExceptionsinnerExceptionclassName { get; set; }
            public string exceptioninnerExceptionsinnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionclientConnectionId { get; set; }
            public string exceptioninnerExceptionsinnerExceptionclientConnectionIdkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkBaseHelpUrl { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkBaseHelpUrlkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkEvtID { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkEvtIDkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkEvtSrc { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkEvtSrckeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkLinkId { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkLinkIdkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkProdName { get; set; }
            public string exceptioninnerExceptionsinnerExceptiondatahelpLinkProdNamekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsclass { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorslineNumber { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsmessage { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsmessagekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsnumber { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsprocedure { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsprocedurekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsserver { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsserverkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorssource { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorssourcekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionerrorsstate { get; set; }
            public string exceptioninnerExceptionsinnerExceptionexceptionMethod { get; set; }
            public string exceptioninnerExceptionsinnerExceptionexceptionMethodkeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionhResult { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionclassName { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionclassNamekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionhResult { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionmessage { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionnativeErrorCode { get; set; }
            public string exceptioninnerExceptionsinnerExceptioninnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptionsinnerExceptionmessage { get; set; }
            public string exceptioninnerExceptionsinnerExceptionmessagekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionremoteStackIndex { get; set; }
            public string exceptioninnerExceptionsinnerExceptionsource { get; set; }
            public string exceptioninnerExceptionsinnerExceptionsourcekeyword { get; set; }
            public string exceptioninnerExceptionsinnerExceptionstackTraceString { get; set; }
            public string exceptioninnerExceptionsinnerExceptionstackTraceStringkeyword { get; set; }
            public string exceptioninnerExceptionsmessage { get; set; }
            public string exceptioninnerExceptionsmessagekeyword { get; set; }
            public string exceptioninnerExceptionsremoteStackIndex { get; set; }
            public string exceptioninnerExceptionssource { get; set; }
            public string exceptioninnerExceptionssourcekeyword { get; set; }
            public string exceptioninnerExceptionsstackTraceString { get; set; }
            public string exceptioninnerExceptionsstackTraceStringkeyword { get; set; }
            public string exceptionkeyword { get; set; }
            public string exceptionlineNumber { get; set; }
            public string exceptionlinePosition { get; set; }
            public string exceptionmessage { get; set; }
            public string exceptionmessagekeyword { get; set; }
            public string exceptionobjectName { get; set; }
            public string exceptionobjectNamekeyword { get; set; }
            public string exceptionparamName { get; set; }
            public string exceptionparamNamekeyword { get; set; }
            public string exceptionremoteStackIndex { get; set; }
            public string exceptionremoteStackTraceString { get; set; }
            public string exceptionremoteStackTraceStringkeyword { get; set; }
            public string exceptionres { get; set; }
            public string exceptionreskeyword { get; set; }
            public string exceptionsource { get; set; }
            public string exceptionsourcekeyword { get; set; }
            public string exceptionsourceUri { get; set; }
            public string exceptionsourceUrikeyword { get; set; }
            public string exceptionstackTraceString { get; set; }
            public string exceptionstackTraceStringkeyword { get; set; }
            public string exceptionstatus { get; set; }
            public string exceptionversion { get; set; }
            public string exceptionversionkeyword { get; set; }
            public string exceptionwatsonBuckets { get; set; }
            public string exceptionwatsonBucketsskippedcount { get; set; }
            public string exceptionzone { get; set; }
            public string exceptionMessage { get; set; }
            public string exceptionMessagekeyword { get; set; }
            public string exceptionStackTrace { get; set; }
            public string exceptionStackTracekeyword { get; set; }
            public string exceptionType { get; set; }
            public string exceptionTypekeyword { get; set; }
            public string executionTime { get; set; }
            public string executionTimeMs { get; set; }
            public string expired { get; set; }
            public string expiredCount { get; set; }
            public string failedCount { get; set; }
            public string file { get; set; }
            public string filekeyword { get; set; }
            public string fileCount { get; set; }
            public string growerId { get; set; }
            public string growerIdkeyword { get; set; }
            public string host { get; set; }
            public string hostkeyword { get; set; }
            public string implementation { get; set; }
            public string implementationkeyword { get; set; }
            public string importedCount { get; set; }
            public string importedFile { get; set; }
            public string importedFilekeyword { get; set; }
            public string _interface { get; set; }
            public string interfacekeyword { get; set; }
            public string internalId { get; set; }
            public string level { get; set; }
            public string levelkeyword { get; set; }
            public string logger { get; set; }
            public string loggerkeyword { get; set; }
            public string message { get; set; }
            public string messagekeyword { get; set; }
            public string method { get; set; }
            public string methodkeyword { get; set; }
            public string name { get; set; }
            public string namekeyword { get; set; }
            public string _namespace { get; set; }
            public string namespacekeyword { get; set; }
            public string orderCompletedDate { get; set; }
            public string orderCompletedDatekeyword { get; set; }
            public string orderID { get; set; }
            public string orderIDkeyword { get; set; }
            public string orderId { get; set; }
            public string orderIdkeyword { get; set; }
            public string orderRef { get; set; }
            public string orderRefkeyword { get; set; }
            public string orderid { get; set; }
            public string orderidkeyword { get; set; }
            public string output { get; set; }
            public string outputkeyword { get; set; }
            public string parameters { get; set; }
            public string pending { get; set; }
            public string pendingCount { get; set; }
            public string performanceHit { get; set; }
            public string productNumber { get; set; }
            public string productNumberkeyword { get; set; }
            public string reason { get; set; }
            public string reasonkeyword { get; set; }
            public string recipient { get; set; }
            public string recipientkeyword { get; set; }
            public string requestId { get; set; }
            public string requestIdkeyword { get; set; }
            public string result { get; set; }
            public string resultkeyword { get; set; }
            public string rows { get; set; }
            public string shopssHOP1expired { get; set; }
            public string shopssHOP1newest { get; set; }
            public string shopssHOP1newestkeyword { get; set; }
            public string shopssHOP1oldest { get; set; }
            public string shopssHOP1oldestkeyword { get; set; }
            public string shopssHOP1pending { get; set; }
            public string shopssHOP2expired { get; set; }
            public string shopssHOP2pending { get; set; }
            public string shopssHOP3expired { get; set; }
            public string shopssHOP3newest { get; set; }
            public string shopssHOP3newestkeyword { get; set; }
            public string shopssHOP3oldest { get; set; }
            public string shopssHOP3oldestkeyword { get; set; }
            public string shopssHOP3pending { get; set; }
            public string shopssHOP4expired { get; set; }
            public string shopssHOP4newest { get; set; }
            public string shopssHOP4newestkeyword { get; set; }
            public string shopssHOP4oldest { get; set; }
            public string shopssHOP4oldestkeyword { get; set; }
            public string shopssHOP4pending { get; set; }
            public string shopssHOP5expired { get; set; }
            public string shopssHOP5newest { get; set; }
            public string shopssHOP5newestkeyword { get; set; }
            public string shopssHOP5oldest { get; set; }
            public string shopssHOP5oldestkeyword { get; set; }
            public string shopssHOP5pending { get; set; }
            public string shopssHOP6expired { get; set; }
            public string shopssHOP6newest { get; set; }
            public string shopssHOP6newestkeyword { get; set; }
            public string shopssHOP6oldest { get; set; }
            public string shopssHOP6oldestkeyword { get; set; }
            public string shopssHOP6pending { get; set; }
            public string shopssHOP7expired { get; set; }
            public string shopssHOP7newest { get; set; }
            public string shopssHOP7newestkeyword { get; set; }
            public string shopssHOP7oldest { get; set; }
            public string shopssHOP7oldestkeyword { get; set; }
            public string shopssHOP7pending { get; set; }
            public string shopssHOP8expired { get; set; }
            public string shopssHOP8newest { get; set; }
            public string shopssHOP8newestkeyword { get; set; }
            public string shopssHOP8oldest { get; set; }
            public string shopssHOP8oldestkeyword { get; set; }
            public string shopssHOP8pending { get; set; }
            public string shopssHOP9expired { get; set; }
            public string shopssHOP9newest { get; set; }
            public string shopssHOP9newestkeyword { get; set; }
            public string shopssHOP9oldest { get; set; }
            public string shopssHOP9oldestkeyword { get; set; }
            public string shopssHOP9pending { get; set; }
            public string solution { get; set; }
            public string solutionkeyword { get; set; }
            public string status { get; set; }
            public string statuskeyword { get; set; }
            public string statusCode { get; set; }
            public string successCount { get; set; }
            public string tags { get; set; }
            public string tagskeyword { get; set; }
            public DateTime timestamp { get; set; }
            public string totalCount { get; set; }
            public string transactionNumber { get; set; }
            public string transactionNumberkeyword { get; set; }
            public string trigger { get; set; }
            public string triggerkeyword { get; set; }
            public string type { get; set; }
            public string typekeyword { get; set; }
            public string url { get; set; }
            public string urlkeyword { get; set; }
            public string urlFull { get; set; }
            public string urlFullkeyword { get; set; }
            public string urlInternal { get; set; }
            public string urlInternalkeyword { get; set; }
            public string userId { get; set; }
            public string userIdkeyword { get; set; }
            public string userName { get; set; }
            public string userNamekeyword { get; set; }
            public string username { get; set; }
            public string usernamekeyword { get; set; }
        }
    }
}
